/****** Object:  Table [dbo].[InCase_Queries]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE TABLE dbo.InCase_Queries(
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TemplateID] [int] NULL,
	[CreatedStamp] [datetime] NULL,
	[LocationMailingList] [bit] NULL,
	[LocationOwnerRes] [int] NULL,
	[LocationAddressDeliverabilityLevel] [int] NULL,
	[LocationNameType] [int] NULL,
	[TransTypeSales] [bit] NULL,
	[TransTypeMortgages] [bit] NULL,
	[TransIncludeMultiParcelTrans] [bit] NULL,
	[TransExcludeMultiParcelTrans] [bit] NULL,
	[TransSalesType] [varchar](20) NULL,
	[TransSalesTypeOtherIncValidSales] [bit] NULL,
	[TransSalesTypeOtherExcValidSales] [bit] NULL,
	[TransSalesTypeOtherIncNominalSales] [bit] NULL,
	[TransSalesTypeOtherExcNominalSales] [bit] NULL,
	[TransSalesTypeOtherIncForclDeeds] [bit] NULL,
	[TransSalesTypeOtherExcForclDeeds] [bit] NULL,
	[TransSalesTypeOtherIncNonValidSales] [bit] NULL,
	[TransSalesTypeOtherExcNonValidSales] [bit] NULL,
	[TransPurchMoneyMtgsOnly] [bit] NULL,
	[TransRefi2ndMtgsOnly] [bit] NULL,
	[TransRefiHistory] [varchar](20) NULL,
	[TransIntrestType] [varchar](20) NULL,
	[BuildingAmenitiesIncludeExclude] [varchar](20) NULL,
	[MtgAssignTransMatchingLevel] [varchar](20) NULL,
	[MtgDischargeTransMatchingLevel] [varchar](20) NULL,
	[SQLCmd] [varchar](max) NULL,
	[VFPIn] [bit] NULL,
	[VFP_QueryID] [varchar](100) NULL,
	[ExcludeVirtualProperties] [bit] NULL,
	[TransExclMtgSource] [bit] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
