/****** Object:  Table [dbo].[Jobs_PreMergeAdjust]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE TABLE dbo.Jobs_PreMergeAdjust(
	[JobID] [int] IDENTITY(1,1) NOT NULL,
	[CreatedStamp] [datetime] NULL,
	[JobTemplateID] [int] NULL,
	[JobName] [nvarchar](100) NOT NULL,
	[disabled] [bit] NULL,
	[RunAtStamp] [datetime] NULL,
	[StartedStamp] [datetime] NULL,
	[CompletedStamp] [datetime] NULL,
	[FailedStamp] [datetime] NULL,
	[SQLJobID] [uniqueidentifier] NULL,
	[WaitStamp] [datetime] NULL,
	[RecurringTypeID] [int] NULL,
	[CategoryID] [int] NULL,
	[ModeID] [int] NULL,
	[PromptState] [bit] NULL,
	[PromptIssueWeek] [bit] NULL,
	[JobStateID] [int] NULL,
	[JobIssueWeek] [int] NULL,
	[ProcessTypeID] [int] NULL,
	[VFPIn] [bit] NULL,
	[VFPState] [varchar](10) NULL,
	[VFPCCode] [varchar](10) NULL,
	[VFPJobID] [int] NULL,
	[CustID] [int] NULL,
	[xDescription] [varchar](255) NULL,
	[UpdatedStamp] [datetime] NULL,
	[IsTemplate] [bit] NULL,
	[Type] [varchar](50) NULL,
	[PromptIssueMonth] [bit] NULL,
	[PromptCalYear] [bit] NULL,
	[PromptCalPeriod] [bit] NULL
) ON [PRIMARY]
