/****** Object:  Table [dbo].[TP_DTMaster_Table]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE TABLE dbo.TP_DTMaster_Table(
	[Record #] [nvarchar](255) NULL,
	[Record Type] [nvarchar](255) NULL,
	[Registry] [nvarchar](255) NULL,
	[Document Type] [nvarchar](255) NULL,
	[Filing Date] [nvarchar](255) NULL,
	[Book #] [nvarchar](255) NULL,
	[Page #] [nvarchar](255) NULL,
	[Doc Reference#] [nvarchar](255) NULL,
	[Lender Name] [nvarchar](255) NULL,
	[Seller1/Grantor1] [nvarchar](255) NULL,
	[Seller2/Grantor2] [nvarchar](255) NULL,
	[Grantor Relationship] [nvarchar](255) NULL,
	[Buyer1=Borrower1] [nvarchar](255) NULL,
	[Buyer2=Borrower2] [nvarchar](255) NULL,
	[Buyers Relationship] [nvarchar](255) NULL,
	[State] [nvarchar](255) NULL,
	[Town] [nvarchar](255) NULL,
	[Street #] [float] NULL,
	[Street Ext] [nvarchar](255) NULL,
	[Street Name] [nvarchar](255) NULL,
	[Property Type] [nvarchar](255) NULL,
	[Unit #] [nvarchar](255) NULL,
	[Partial/ Multi Sale] [nvarchar](255) NULL,
	[Date of Creation] [nvarchar](255) NULL,
	[Name of Signer] [nvarchar](255) NULL,
	[Mailing address of Buyer] [nvarchar](255) NULL,
	[Sales Amount] [nvarchar](255) NULL,
	[Orginal Lender Name] [nvarchar](255) NULL,
	[Mtg Amount] [nvarchar](255) NULL,
	[Orginal Mtg Book] [nvarchar](255) NULL,
	[Orginal Mtg Page] [nvarchar](255) NULL,
	[Orginal Mtg Date] [nvarchar](255) NULL,
	[term] [nvarchar](255) NULL,
	[Defendant1] [nvarchar](255) NULL,
	[initial interest rate] [float] NULL,
	[Defendent2] [nvarchar](255) NULL,
	[index name] [nvarchar](255) NULL,
	[Alias] [nvarchar](255) NULL,
	[Alias Relationship] [nvarchar](255) NULL,
	[change date] [nvarchar](255) NULL,
	[calc of change] [nvarchar](255) NULL,
	[Def Relationship] [nvarchar](255) NULL,
	[Plaintiff1] [nvarchar](255) NULL,
	[Plaintiff2] [nvarchar](255) NULL,
	[Orginal Mtg doc number] [nvarchar](255) NULL,
	[Amount] [nvarchar](255) NULL,
	[Tax/Lien Type] [nvarchar](255) NULL,
	[Mtg1 Lender] [nvarchar](255) NULL,
	[Mtg1 Lender Misc] [nvarchar](255) NULL,
	[Mtg1 Book] [nvarchar](255) NULL,
	[Mtg1 Page] [nvarchar](255) NULL,
	[Mtg1 Amount] [nvarchar](255) NULL,
	[Mtg1 Term] [nvarchar](255) NULL,
	[Mtg1 Interest] [float] NULL,
	[Mtg1 Type] [nvarchar](255) NULL,
	[Mtg1 Index Name] [nvarchar](255) NULL,
	[Mtg1 Change Date] [nvarchar](255) NULL,
	[Mtg1 Calc of Change] [float] NULL,
	[Mtg1 Rider Type] [nvarchar](255) NULL,
	[Mtg1 modification original amt] [nvarchar](255) NULL,
	[Mtg1 modication new amount] [nvarchar](255) NULL,
	[Mtg1 MERS MIN#] [nvarchar](255) NULL,
	[Mtg1 FHA/VA #] [nvarchar](255) NULL,
	[Mtg1 originators #] [nvarchar](255) NULL,
	[Mtg1 orginators name] [nvarchar](255) NULL,
	[Mtg1 Brokers #] [nvarchar](255) NULL,
	[Mtg1 Brokers Name] [nvarchar](255) NULL,
	[Mtg2 Lender] [nvarchar](255) NULL,
	[Mtg2 Lender Misc] [nvarchar](255) NULL,
	[Mtg2 Book] [nvarchar](255) NULL,
	[Mtg2 Page] [nvarchar](255) NULL,
	[Mtg2 Amount] [nvarchar](255) NULL,
	[Mtg2 Term] [nvarchar](255) NULL,
	[Mtg2 Interest] [float] NULL,
	[Mtg2 Type] [nvarchar](255) NULL,
	[Mtg2 Index Name] [nvarchar](255) NULL,
	[Mtg2 Change Date] [nvarchar](255) NULL,
	[Mtg2 Calc of Change] [float] NULL,
	[Mtg2 Rider Type] [nvarchar](255) NULL,
	[Mtg2 modification original amt] [nvarchar](255) NULL,
	[Mtg2 modication new amount] [nvarchar](255) NULL,
	[Mtg2 MERS MIN#] [nvarchar](255) NULL,
	[Mtg2 FHA/VA #] [nvarchar](255) NULL,
	[Mtg2 originators #] [nvarchar](255) NULL,
	[Mtg2 orginators name] [nvarchar](255) NULL,
	[Mtg2 Brokers #] [nvarchar](255) NULL,
	[Mtg2 Brokers Name] [nvarchar](255) NULL,
	[Mtg3 Lender] [nvarchar](255) NULL,
	[Mtg3 Lender Misc] [nvarchar](255) NULL,
	[Mtg3 Book] [nvarchar](255) NULL,
	[Mtg3 Page] [nvarchar](255) NULL,
	[Mtg3 Amount] [nvarchar](255) NULL,
	[Mtg3 Term] [nvarchar](255) NULL,
	[Mtg3 Interest] [float] NULL,
	[Mtg3 Type] [nvarchar](255) NULL,
	[Mtg3 Index Name] [nvarchar](255) NULL,
	[Mtg3 Change Date] [nvarchar](255) NULL,
	[Mtg3 Calc of Change] [float] NULL,
	[Mtg3 Rider Type] [nvarchar](255) NULL,
	[Mtg3 modification original amt] [nvarchar](255) NULL,
	[Mtg3 modication new amount] [nvarchar](255) NULL,
	[Mtg3 MERS MIN#] [nvarchar](255) NULL,
	[Mtg3 FHA/VA #] [nvarchar](255) NULL,
	[Mtg3 originators #] [nvarchar](255) NULL,
	[Mtg3 orginators name] [nvarchar](255) NULL,
	[Mtg3 Brokers #] [nvarchar](255) NULL,
	[Mtg3 Brokers Name] [nvarchar](255) NULL,
	[MERS Indicator] [nvarchar](255) NULL,
	[MERS NUMBER] [nvarchar](255) NULL,
	[Discharge Borrower1 ID] [nvarchar](255) NULL,
	[Discharge Borrower2 ID] [nvarchar](255) NULL,
	[Assignor Security Name] [nvarchar](255) NULL,
	[Assignor Trustee Name] [nvarchar](255) NULL,
	[Assignee Security Name] [nvarchar](255) NULL,
	[Assignee Trustee Name] [nvarchar](255) NULL,
	[Discharge Lender Trustee Name] [nvarchar](255) NULL,
	[Discharge Orig Contract Date] [nvarchar](255) NULL,
	[Discharge Loan Number] [nvarchar](255) NULL,
	[Discharge Loan AMount] [float] NULL,
	[Discharge Loan Payoff Date] [nvarchar](255) NULL,
	[MERS NUMBER DID NOT PASS VALIDATION] [nvarchar](255) NULL,
	[Assignment Doc Type] [nvarchar](255) NULL,
	[Discharge Doc Type] [nvarchar](255) NULL,
	[LENDER IN RECEIVERSHIP] [nvarchar](255) NULL,
	[ZipCodeNY] [nvarchar](255) NULL,
	[Assignment Loan Number] [nvarchar](255) NULL,
	[Pool#] [nvarchar](255) NULL,
	[VillageName] [nvarchar](255) NULL,
	[DocImageUnavailable] [bit] NOT NULL,
	[RECORD DATE] [datetime] NULL,
	[Modification Date] [nvarchar](255) NULL,
	[Remarks] [nvarchar](255) NULL,
	[Reporter] [nvarchar](255) NULL,
	[Transmission Date] [datetime] NULL,
	[Mtg1 Type Other] [nvarchar](255) NULL,
	[Mtg2 Type Other] [nvarchar](255) NULL,
	[Mtg3 Type Other] [nvarchar](255) NULL,
	[MtgType1A] [nvarchar](255) NULL,
	[MtgType2A] [nvarchar](255) NULL,
	[MtgType3A] [nvarchar](255) NULL,
	[Title of Signer] [nvarchar](255) NULL,
	[Company Name of Signer] [nvarchar](255) NULL,
	[Signer Street #] [nvarchar](255) NULL,
	[Signer Street Ext] [nvarchar](255) NULL,
	[Signer Street Name] [nvarchar](255) NULL,
	[Signer Unit] [nvarchar](255) NULL,
	[Signner Property Type] [nvarchar](255) NULL,
	[Signer Zip Code] [nvarchar](255) NULL,
	[Signer Town] [nvarchar](255) NULL,
	[Signer Village] [nvarchar](255) NULL,
	[SignerState] [nvarchar](255) NULL,
	[Parcel ID 1] [nvarchar](255) NULL,
	[Parcel ID 2] [nvarchar](255) NULL,
	[Parcel ID 3] [nvarchar](255) NULL,
	[Parcel ID 4] [nvarchar](255) NULL,
	[Parcel ID 5] [nvarchar](255) NULL,
	[Employee#] [nvarchar](255) NULL,
	[Batch#] [float] NULL,
	[ClosedTowns] [nvarchar](255) NULL,
	[MERSFLAG1] [bit] NOT NULL,
	[MERSFLAG2] [bit] NOT NULL,
	[MERSFLAG3] [bit] NOT NULL,
	[PickTowns] [nvarchar](255) NULL,
	[M1] [nvarchar](255) NULL,
	[M2] [nvarchar](255) NULL,
	[M3] [nvarchar](255) NULL,
	[M4] [nvarchar](255) NULL,
	[M5] [nvarchar](255) NULL,
	[M6] [nvarchar](255) NULL,
	[M7] [nvarchar](255) NULL,
	[M8] [nvarchar](255) NULL,
	[M9] [nvarchar](255) NULL,
	[M10] [nvarchar](255) NULL,
	[M11] [nvarchar](255) NULL,
	[M12] [nvarchar](255) NULL,
	[M13] [nvarchar](255) NULL,
	[M14] [nvarchar](255) NULL,
	[M15] [nvarchar](255) NULL,
	[M16] [nvarchar](255) NULL,
	[M17] [nvarchar](255) NULL,
	[M18] [nvarchar](255) NULL,
	[Research] [nvarchar](255) NULL,
	[Record # TS] [nvarchar](255) NULL,
	[Record Date TS] [nvarchar](255) NULL,
	[Begin Time TS] [nvarchar](255) NULL,
	[End Time TS] [nvarchar](255) NULL,
	[# of Hours TS] [nvarchar](255) NULL,
	[Town TS] [nvarchar](255) NULL,
	[Comments TS] [nvarchar](255) NULL,
	[Employee# TS] [nvarchar](255) NULL,
	[ReporterName TS] [nvarchar](255) NULL,
	[ReporterState TS] [nvarchar](255) NULL,
	[Record Stampdate TS] [nvarchar](255) NULL,
	[TransmissionDate TS] [nvarchar](255) NULL,
	[Batch# TS] [nvarchar](255) NULL,
	[Type TS] [nvarchar](255) NULL,
	[DT Type] [nvarchar](255) NULL,
	[Check #] [nvarchar](255) NULL,
	[BP-Contractors Address] [nvarchar](255) NULL,
	[BP-Contractors Phone #] [nvarchar](255) NULL,
	[BP-Permit Fees_Cost] [nvarchar](255) NULL,
	[BP-Square Footage] [nvarchar](255) NULL,
	[BP-Misc1] [nvarchar](255) NULL,
	[BP-Misc2] [nvarchar](255) NULL,
	[BP-Misc3] [nvarchar](255) NULL,
	[BP-Misc4] [nvarchar](255) NULL,
	[BP-Misc5] [nvarchar](255) NULL,
	[Lot 1 Description] [nvarchar](255) NULL,
	[Lot 2 Description] [nvarchar](255) NULL,
	[Lot Size 1] [nvarchar](255) NULL,
	[Lot Size 2] [nvarchar](255) NULL,
	[Date of Deed] [nvarchar](255) NULL,
	[Lot Number 1] [nvarchar](255) NULL,
	[Lot Number 2] [nvarchar](255) NULL,
	[# of Parcels] [nvarchar](255) NULL,
	[Plan Reference Number] [nvarchar](255) NULL,
	[Property Description Code Number] [nvarchar](255) NULL,
	[Stamp Amount] [nvarchar](255) NULL,
	[Stamp Code] [nvarchar](255) NULL,
	[Conveyance Rate] [nvarchar](255) NULL,
	[AuctionDateTime] [nvarchar](255) NULL,
	[AttorneyAddress] [nvarchar](255) NULL,
	[AuctionTerm] [nvarchar](255) NULL,
	[Tax/Lien Type2] [nvarchar](255) NULL,
	[AttorneyNH] [nvarchar](255) NULL,
	[Land Court] [bit] NOT NULL
) ON [PRIMARY]
